// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  rpcApiSidebar: [
    {
      type: 'doc',
      label: 'RPC API Overview',
      id: 'rpc-api/rpc-api-landing',
    },
    {
      type: 'doc',
      label: 'API Reference',
      id: 'rpc-api/api',
    },
    {
      type: 'doc',
      label: 'RPC Methods',
      id: 'rpc-api/rpc'
    },
    {
      type: 'category',
      label: 'Account',
      items: [
        'rpc-api/account/view-account',
      ],
    },
  ],
  snapshotsSidebars: [{type: 'autogenerated', dirName: 'snapshots'}],
};

export default sidebars;
