// @ts-check

/**
 * @type {import('@docusaurus/plugin-content-docs').SidebarsConfig}
 */

const sidebars = {
  transactionFlowSidebar: [{ type: 'autogenerated', dirName: 'transaction-flow' }],
  rpcApiSidebar: [
    {
      type: 'category',
      label: 'Account',
      items: [
        'rpc-api/account/view-account',
        'rpc-api/account/view-access-key',
        'rpc-api/account/view-access-key-list',
      ],
    },
    {
      type: 'category',
      label: 'Block',
      items: [
        'rpc-api/block/block-by-height',
        'rpc-api/block/block-by-id',
        'rpc-api/block/block-effects',
      ],
    },
    {
      type: 'category',
      label: 'Contract',
      items: [
        'rpc-api/contract/call-function',
        'rpc-api/contract/view-code',
        'rpc-api/contract/view-state',
        'rpc-api/contract/view-global-contract-code',
        'rpc-api/contract/view-global-contract-code-by-account-id',
      ],
    },
    {
      type: 'category',
      label: 'Protocol',
      items: [
        'rpc-api/protocol/status',
        'rpc-api/protocol/health',
        'rpc-api/protocol/gas-price',
        'rpc-api/protocol/gas-price-by-block',
        'rpc-api/protocol/genesis-config',
        'rpc-api/protocol/changes',
        'rpc-api/protocol/chunk-by-hash',
        'rpc-api/protocol/chunk-by-block-shard',
        'rpc-api/protocol/client-config',
        'rpc-api/protocol/network-info',
        'rpc-api/protocol/latest-block',
        'rpc-api/protocol/metrics',
        'rpc-api/protocol/maintenance-windows',
        'rpc-api/protocol/light-client-proof',
        'rpc-api/protocol/next-light-client-block',
        'rpc-api/protocol/experimental-protocol-config',
        'rpc-api/protocol/experimental-congestion-level',
        'rpc-api/protocol/experimental-light-client-block-proof',
        'rpc-api/protocol/experimental-light-client-proof',
        'rpc-api/protocol/experimental-split-storage-info',
      ],
    },
    {
      type: 'category',
      label: 'Transaction',
      items: [
        'rpc-api/transaction/tx-status',
        'rpc-api/transaction/send-tx',
        'rpc-api/transaction/broadcast-tx-async',
        'rpc-api/transaction/broadcast-tx-commit',
        'rpc-api/transaction/experimental-receipt',
        'rpc-api/transaction/experimental-tx-status',
      ],
    },
    {
      type: 'category',
      label: 'Validators',
      items: [
        'rpc-api/validators/validators-current',
        'rpc-api/validators/validators-by-epoch',
        'rpc-api/validators/experimental-validators-ordered',
      ],
    },
  ],
  snapshotsSidebars: [{type: 'autogenerated', dirName: 'snapshots'}],
};

export default sidebars;
